CREATE TABLE `ccs_acct_o_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` char(1) NOT NULL DEFAULT '' COMMENT '账户类型',
  `currency` char(3) NOT NULL DEFAULT '' COMMENT '币种',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `auth_tag` varchar(255) NOT NULL DEFAULT '' COMMENT '授权标识',
  `policy_ind` char(1) NOT NULL DEFAULT '' COMMENT '限额开关',
  `blk_cd_auth` varchar(27) NOT NULL DEFAULT '' COMMENT '授权锁定码',
  `blk_cd_post` varchar(27) NOT NULL DEFAULT '' COMMENT '账务锁定码',
  `last_matched_overnight_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '上次隔日匹配的业务日期',
  `last_update_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '上次联机更新业务日期',
  `owning_branch` varchar(9) NOT NULL DEFAULT '' COMMENT '发卡网点',
  `stmt_day` int(11) NOT NULL DEFAULT '0' COMMENT '账单日',
  `sms_ind` char(1) NOT NULL DEFAULT '' COMMENT '短信发送标识',
  `user_sms_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '个性化动账短信发送阈值',
  `float_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '浮动比例',
  `single_curr_settl_ind` char(1) NOT NULL DEFAULT '' COMMENT '单一货币结算标识 ',
  `retail_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '刷卡金使用金额',
  `retail_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '刷卡金',
  `credit_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '还款金',
  `acct_limit` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '账户限额额度',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `acct_mon_limit` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '账户月限额',
  `acct_mon_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '账户月累计金额',
  `acct_mon_limit_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '账户月限额开关',
  `test` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为测试数据：0-否；1-是',
  `shadow_lmt_usage` varchar(16) NOT NULL DEFAULT 'UNLIMITED' COMMENT '账户层影子额度使用方式',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq__ccs_acct_o` (`acct_nbr`,`acct_type`) USING BTREE,
  KEY `idx_cust_id` (`cust_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_acct_o' ;
CREATE TABLE `ccs_acct_scene_policy_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构编号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `currency` char(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `policy_tag` varchar(16) NOT NULL DEFAULT '' COMMENT '限额标签',
  `lt_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单笔限额',
  `st_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单笔限额',
  `st_txn_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额开始日期',
  `st_txn_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额结束日期',
  `lt_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单日限笔',
  `st_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单日限笔',
  `st_day_cnt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔开始日期',
  `st_day_cnt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔结束日期',
  `lt_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单日限额',
  `st_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单日限额',
  `st_day_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额开始日期',
  `st_day_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额结束日期',
  `lt_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单月限额',
  `st_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单月限额',
  `st_mon_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额开始日期',
  `st_mon_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额结束日期',
  `lt_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单年限额',
  `st_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单年限额',
  `st_year_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额开始日期',
  `st_year_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额结束日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `lt_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单月限笔',
  `st_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单月限笔',
  `st_mon_cnt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限笔开始日期',
  `st_mon_cnt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限笔结束日期',
  `auth_ind` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '是否支持本币交易',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq__ccs_acct_scene_policy` (`acct_nbr`,`currency`,`txn_scene`,`policy_tag`) USING BTREE,
  KEY `idx_acct_currency_scene` (`acct_nbr`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_acct_scene_policy' ;
CREATE TABLE `ccs_acct_scene_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` char(1) NOT NULL DEFAULT '' COMMENT '账户类型',
  `currency` char(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `dtd_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当日累计笔数',
  `dtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日累计金额',
  `mon_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当月累计笔数',
  `mtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当月累计金额',
  `ytd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当年累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_acct_scene_stat` (`acct_nbr`,`acct_type`,`currency`,`txn_scene`) USING BTREE,
  KEY `idx_acct_currency_scene` (`acct_nbr`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_acct_scene_stat' ;
CREATE TABLE `auth_order_hst_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '授权流水号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` char(1) NOT NULL DEFAULT '' COMMENT '账户类型',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `lmt_node_cd` varchar(32) NOT NULL DEFAULT '' COMMENT '额度节点',
  `lmt_type` varchar(16) NOT NULL DEFAULT '' COMMENT '额度类型',
  `acq_ref_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '受理机构交易编码',
  `txn_scene_list` varchar(255) NOT NULL DEFAULT '' COMMENT '交易场景列表',
  `txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '交易金额',
  `txn_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '交易币种代码',
  `auth_code` varchar(6) NOT NULL DEFAULT '' COMMENT '授权码',
  `loan_code` varchar(16) NOT NULL DEFAULT '' COMMENT '分期产品代码',
  `acq_address` varchar(64) NOT NULL DEFAULT '' COMMENT '受理机构名称地址',
  `chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '持卡人账户币种金额',
  `chb_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '持卡人账户币种',
  `input_source` varchar(15) NOT NULL DEFAULT '' COMMENT '交易渠道',
  `mcc` varchar(4) NOT NULL DEFAULT '' COMMENT '商户类型',
  `acq_branch_iq` varchar(11) NOT NULL DEFAULT '' COMMENT '受理分行代码',
  `fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '转发机构号',
  `transport_time` varchar(10) NOT NULL DEFAULT '' COMMENT '传送日期',
  `settle_date` varchar(4) NOT NULL DEFAULT '' COMMENT '清算日期',
  `txn_direction` varchar(20) NOT NULL DEFAULT '' COMMENT '交易方向',
  `auth_txn_terminal` varchar(40) NOT NULL DEFAULT '' COMMENT '交易终端',
  `auth_txn_status` char(1) NOT NULL DEFAULT '' COMMENT '授权状态',
  `txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '交易类型',
  `log_ol_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT 'log联机时间',
  `log_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '联机业务日期',
  `mti` char(4) NOT NULL DEFAULT '' COMMENT '交易类型标识',
  `orig_txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '原交易类型',
  `orig_fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始转发机构号',
  `orig_acq_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始受理机构号',
  `orig_mti` varchar(4) NOT NULL DEFAULT '' COMMENT '原交易mti',
  `orig_txn_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易日期',
  `orig_trace_no` varchar(6) NOT NULL DEFAULT '' COMMENT '原始系统跟踪号',
  `orig_txn_proc` char(6) NOT NULL DEFAULT '' COMMENT '原交易处理码',
  `orig_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始交易币种金额',
  `orig_log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '原交易log键值',
  `orig_txn_val_1` varchar(38) NOT NULL DEFAULT '' COMMENT '原交易键值1',
  `orig_txn_val_2` varchar(85) NOT NULL DEFAULT '' COMMENT '原交易键值2',
  `orig_chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始入账币种金额',
  `orig_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易的联机业务处理日期',
  `last_reversal_date` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '最后一次冲撤时间',
  `void_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '撤销次数',
  `manual_auth_flag` char(1) NOT NULL DEFAULT '' COMMENT '人工授权标志',
  `op_id` varchar(40) NOT NULL DEFAULT '' COMMENT '操作员id',
  `card_association` varchar(2) NOT NULL DEFAULT '' COMMENT '卡组织品牌',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `mcc_type` char(2) NOT NULL DEFAULT '' COMMENT '商户类型分组',
  `final_reason` char(4) NOT NULL DEFAULT '' COMMENT '授权原因',
  `final_action` char(1) NOT NULL DEFAULT '' COMMENT '最终行动',
  `final_auth_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终授权金额',
  `final_upd_direction` char(1) NOT NULL DEFAULT '' COMMENT '最终更新方向',
  `final_upd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终更新金额',
  `ic_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否ic卡',
  `the_3dsecure_type` char(1) NOT NULL DEFAULT '' COMMENT '是否3d电子安全交易',
  `vip_status` char(1) NOT NULL DEFAULT '' COMMENT 'vip状态',
  `curr_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当前余额',
  `cash_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现金额',
  `otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '可用额度',
  `cash_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现可用额度',
  `cust_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '客户可用额度',
  `in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '账户黑名单标识',
  `mer_in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '是否商户黑名单',
  `date_expire` char(4) NOT NULL DEFAULT '' COMMENT '卡面有效期',
  `megt1_result` varchar(20) NOT NULL DEFAULT '' COMMENT '一磁道完整性结果',
  `megt2_result` varchar(20) NOT NULL DEFAULT '' COMMENT '二磁道完整性结果',
  `megt3_result` varchar(20) NOT NULL DEFAULT '' COMMENT '三磁道完整性结果',
  `pwd_type` char(1) NOT NULL DEFAULT '' COMMENT '密码种类',
  `pwd_result` varchar(20) NOT NULL DEFAULT '' COMMENT '验证密码结果',
  `pay_pwd_err_num` int(11) NOT NULL DEFAULT '0' COMMENT '支付密码错误次数',
  `cvv_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv验证结果',
  `cvv2_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv2验证结果',
  `icvn_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'icvn验证结果',
  `arqc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'arqc验证结果',
  `atc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'atc验证结果',
  `cvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvr验证结果',
  `tvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'tvr验证结果',
  `rej_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '拒绝原因',
  `memo_cr` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配贷记金额',
  `memo_db` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配借记金额',
  `b002_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '介质卡号-b002',
  `b003_proc_code` varchar(6) NOT NULL DEFAULT '' COMMENT '交易处理码-b003',
  `b004_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '交易金额-B004',
  `b007_txn_time` varchar(10) NOT NULL DEFAULT '' COMMENT '交易传输时间-b007',
  `b011_trace` char(6) NOT NULL DEFAULT '' COMMENT '系统跟踪号-b011',
  `b022_entrymode` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点pin获取码-b022',
  `b025_entrycond` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点条件码-b025',
  `b032_acq_inst` varchar(15) NOT NULL DEFAULT '' COMMENT '受理机构标识码-b032',
  `b033_fwd_ins` varchar(40) NOT NULL DEFAULT '' COMMENT '受理机构名称地址-b033',
  `b039_rtn_code` varchar(2) NOT NULL DEFAULT '' COMMENT '返回码-b039',
  `b042_mer_id` varchar(15) NOT NULL DEFAULT '' COMMENT '受卡方(商户)标识码-b042',
  `b060_reserved` varchar(103) NOT NULL DEFAULT '' COMMENT '自定义域-b060',
  `b061_cust_info` varchar(203) NOT NULL DEFAULT '' COMMENT '持卡人身份认证信息-b061',
  `b090_orig_data` varchar(42) NOT NULL DEFAULT '' COMMENT '原始数据元',
  `op_term_id` varchar(20) NOT NULL DEFAULT '' COMMENT '操作用户终端编号',
  `b006_chb_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '账户货币金额-B006',
  `b049_curr_code` char(3) NOT NULL DEFAULT '' COMMENT '交易货币代码-b049',
  `b051_chb_curr_code` char(3) NOT NULL DEFAULT '' COMMENT '账户货币代码-b051',
  `b037_ref_nbr` char(12) NOT NULL DEFAULT '' COMMENT '检索参考号-b037',
  `b028_fee` varchar(9) NOT NULL DEFAULT '' COMMENT '手续费-B028',
  `b048_add` varchar(999) NOT NULL DEFAULT '' COMMENT '附加数据-b048',
  `b054_resp` varchar(60) NOT NULL DEFAULT '' COMMENT '返回余额数组-b054',
  `b063_network_data` varchar(20) NOT NULL DEFAULT '' COMMENT '网络数据-b063',
  `acq_terminal_id` varchar(8) NOT NULL DEFAULT '' COMMENT '受理机构终端标识码',
  `post_online` char(1) NOT NULL DEFAULT '' COMMENT '联机入账标识',
  `match_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否匹配',
  `b056` varchar(20) NOT NULL DEFAULT '' COMMENT '56域',
  `trans_medium` varchar(32) NOT NULL DEFAULT '' COMMENT '交易介质',
  `conversion_rt` decimal(8,6) NOT NULL DEFAULT '0.000000' COMMENT '兑换汇率',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `b019` varchar(20) NOT NULL DEFAULT '' COMMENT 'b019',
  `b095_replace_amt` varchar(42) NOT NULL DEFAULT '' COMMENT 'B95替换金额',
  `b112_addl_data` varchar(100) NOT NULL DEFAULT '' COMMENT 'B112附加数据',
  `b121_auth_agentid` varchar(6) NOT NULL DEFAULT '' COMMENT 'B121授权代理ID代码',
  `txn_desc` varchar(64) NOT NULL DEFAULT '' COMMENT '交易描述',
  `amt_direction` varchar(3) NOT NULL DEFAULT '' COMMENT '金额方向',
  `show_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '对客展示标识',
  `b013_local_date` varchar(4) NOT NULL DEFAULT '' COMMENT 'DE13域本地交易日期MMDD',
  `b012_local_time` varchar(6) NOT NULL DEFAULT '' COMMENT 'DE12本地交易时间HHMMSS',
  `b4842_ecommerce_ind` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4842电子商务指标',
  `b4843_ucaf` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4843通用持卡人身份验证',
  `b4866_auth_data` varchar(45) NOT NULL DEFAULT '' COMMENT 'DE4866认证数据',
  `b4871_ob_services` varchar(40) NOT NULL DEFAULT '' COMMENT 'DE4871交易支持服务',
  `b4875_fraud_score` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4875交易风险评分',
  `cvm_result_9f34` varchar(6) NOT NULL DEFAULT '' COMMENT 'DE55_9F34',
  `loan_term` int(11) NOT NULL DEFAULT '0' COMMENT '分期期数',
  `b0120` varchar(1024) NOT NULL DEFAULT '' COMMENT 'DE120域',
  `b0124` varchar(1024) NOT NULL DEFAULT '' COMMENT 'DE124域',
  `b122_addl` varchar(999) NOT NULL DEFAULT '' COMMENT 'DE122',
  `virtual_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '虚拟卡标识',
  `advice_de39` varchar(2) NOT NULL DEFAULT '' COMMENT '通知交易39域信息',
  `auth_reason_list` varchar(999) NOT NULL DEFAULT '' COMMENT '授权原因码列表',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_authmemo_hst` (`log_kv`) USING BTREE,
  KEY `idx_ccs_authmemo_hst_1` (`acct_nbr`) USING BTREE,
  KEY `idx_ci_tc` (`cust_id`,`txn_currency`),
  KEY `idx_logic_number` (`logic_card_nbr`),
  KEY `idx_match_ind` (`match_ind`),
  KEY `idx_log_biz_date` (`log_biz_date`),
  KEY `idx_log_ol_time` (`log_ol_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_authmemo_hst' ;
alter table `auth_order_hst_{0,255}` add column `stat_lmt_scene_list` varchar(2048) NOT NULL DEFAULT '' COMMENT '累计限额场景列表' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `txn_input_source` varchar(40) NOT NULL DEFAULT '' COMMENT '交易来源' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `bound` varchar(2) NOT NULL DEFAULT '' COMMENT '境内外标记' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `counterpart_no` varchar(40) NOT NULL DEFAULT '' COMMENT '对方账号卡号' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `counterpart_name` varchar(40) NOT NULL DEFAULT '' COMMENT '对方名称' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `counterpart_address` varchar(80) NOT NULL DEFAULT '' COMMENT '对方地址' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `retail_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '刷卡金使用金额' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column `credit_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '还款金使用金额' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `mer_data` varchar(200) NOT NULL DEFAULT '' COMMENT '商户信息' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `assign_pay_branch_nbr` varchar(15) NOT NULL DEFAULT '' COMMENT '指定部门还款部门号' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `txn_attribute` varchar(300) NOT NULL DEFAULT '' COMMENT '交易附属信息' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `orig_trace_nbr` varchar(6) NOT NULL DEFAULT '' COMMENT '原交易系统跟踪号' after `conversion_rt`;
alter table `auth_order_hst_{0,255}` add column  `orig_local_time` varchar(14) NOT NULL DEFAULT '' COMMENT '原交易报文日期时间' after `conversion_rt`;
CREATE TABLE `ccs_authmemo_inq_log_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '授权流水号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` char(1) NOT NULL DEFAULT '' COMMENT '账户类型',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `acq_ref_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '受理机构交易编码',
  `txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '交易金额',
  `txn_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '交易币种代码',
  `auth_code` varchar(6) NOT NULL DEFAULT '' COMMENT '授权码',
  `acq_address` varchar(64) NOT NULL DEFAULT '' COMMENT '受理机构名称地址',
  `chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '持卡人账户币种金额',
  `chb_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '持卡人账户币种',
  `input_source` varchar(15) NOT NULL DEFAULT '' COMMENT '交易渠道',
  `mcc` varchar(4) NOT NULL DEFAULT '' COMMENT '商户类型',
  `acq_branch_iq` varchar(11) NOT NULL DEFAULT '' COMMENT '受理分行代码',
  `fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '转发机构号',
  `transport_time` varchar(10) NOT NULL DEFAULT '' COMMENT '传送日期',
  `settle_date` varchar(4) NOT NULL DEFAULT '' COMMENT '清算日期',
  `txn_direction` varchar(20) NOT NULL DEFAULT '' COMMENT '交易方向',
  `auth_txn_terminal` varchar(40) NOT NULL DEFAULT '' COMMENT '交易终端',
  `auth_txn_status` char(1) NOT NULL DEFAULT '' COMMENT '授权状态',
  `txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '交易类型',
  `log_ol_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT 'log联机时间',
  `log_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '联机业务日期',
  `mti` varchar(4) NOT NULL DEFAULT '' COMMENT '交易类型标识',
  `orig_trace_no` varchar(6) NOT NULL DEFAULT '' COMMENT '原始系统跟踪号',
  `orig_acq_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始受理机构号',
  `orig_fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始转发机构号',
  `orig_txn_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易日期',
  `orig_txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '原交易类型',
  `orig_mti` varchar(4) NOT NULL DEFAULT '' COMMENT '原交易mti',
  `orig_txn_proc` varchar(6) NOT NULL DEFAULT '' COMMENT '原交易处理码',
  `orig_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始交易币种金额',
  `orig_log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '原交易log键值',
  `orig_txn_val_1` varchar(38) NOT NULL DEFAULT '' COMMENT '原交易键值1',
  `orig_txn_val_2` varchar(40) NOT NULL DEFAULT '' COMMENT '原交易键值2',
  `orig_chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始入账币种金额',
  `orig_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易的联机业务处理日期',
  `last_reversal_date` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '最后一次冲撤时间',
  `void_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '撤销次数',
  `manual_auth_flag` char(1) NOT NULL DEFAULT '' COMMENT '人工授权标志',
  `op_id` varchar(40) NOT NULL DEFAULT '' COMMENT '操作员id',
  `card_association` varchar(2) NOT NULL DEFAULT '' COMMENT '卡组织品牌',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `mcc_type` varchar(2) NOT NULL DEFAULT '' COMMENT '商户类型分组',
  `final_reason` varchar(4) NOT NULL DEFAULT '' COMMENT '授权原因',
  `final_action` char(1) NOT NULL DEFAULT '' COMMENT '最终行动',
  `final_auth_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终授权金额',
  `final_upd_direction` char(1) NOT NULL DEFAULT '' COMMENT '最终更新方向',
  `final_upd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终更新金额',
  `ic_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否ic卡',
  `the_3dsecure_type` char(1) NOT NULL DEFAULT '' COMMENT '是否3d电子安全交易',
  `vip_status` char(1) NOT NULL DEFAULT '' COMMENT 'vip状态',
  `curr_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当前余额',
  `otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '可用额度',
  `cash_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现金额',
  `cash_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现可用额度',
  `cust_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '客户可用额度',
  `in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '账户黑名单标识',
  `mer_in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '是否商户黑名单',
  `date_expire` varchar(4) NOT NULL DEFAULT '' COMMENT '卡面有效期',
  `megt1_result` varchar(20) NOT NULL DEFAULT '' COMMENT '一磁道完整性结果',
  `megt2_result` varchar(20) NOT NULL DEFAULT '' COMMENT '二磁道完整性结果',
  `megt3_result` varchar(20) NOT NULL DEFAULT '' COMMENT '三磁道完整性结果',
  `pwd_type` char(1) NOT NULL DEFAULT '' COMMENT '密码种类',
  `pwd_result` varchar(20) NOT NULL DEFAULT '' COMMENT '验证密码结果',
  `pay_pwd_err_num` int(11) NOT NULL DEFAULT '0' COMMENT '支付密码错误次数',
  `cvv_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv验证结果',
  `cvv2_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv2验证结果',
  `icvn_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'icvn验证结果',
  `arqc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'arqc验证结果',
  `atc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'atc验证结果',
  `cvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvr验证结果',
  `tvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'tvr验证结果',
  `rej_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '拒绝原因',
  `memo_cr` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配贷记金额',
  `memo_db` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配借记金额',
  `b002_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '介质卡号-b002',
  `b003_proc_code` varchar(6) NOT NULL DEFAULT '' COMMENT '交易处理码-b003',
  `b004_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '交易金额-B004',
  `b007_txn_time` varchar(10) NOT NULL DEFAULT '' COMMENT '交易传输时间-b007',
  `b011_trace` varchar(6) NOT NULL DEFAULT '' COMMENT '系统跟踪号-b011',
  `b022_entrymode` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点pin获取码-b022',
  `b025_entrycond` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点条件码-b025',
  `b032_acq_inst` varchar(15) NOT NULL DEFAULT '' COMMENT '受理机构标识码-b032',
  `b033_fwd_ins` varchar(40) NOT NULL DEFAULT '' COMMENT '受理机构名称地址-b033',
  `b039_rtn_code` varchar(2) NOT NULL DEFAULT '' COMMENT '返回码-b039',
  `b042_mer_id` varchar(15) NOT NULL DEFAULT '' COMMENT '受卡方(商户)标识码-b042',
  `b060_reserved` varchar(103) NOT NULL DEFAULT '' COMMENT '自定义域-b060',
  `b061_cust_info` varchar(203) NOT NULL DEFAULT '' COMMENT '持卡人身份认证信息-b061',
  `b090_orig_data` varchar(42) NOT NULL DEFAULT '' COMMENT '原始数据元',
  `op_term_id` varchar(20) NOT NULL DEFAULT '' COMMENT '操作用户终端编号',
  `b006_chb_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '账户货币金额-B006',
  `b049_curr_code` varchar(3) NOT NULL DEFAULT '' COMMENT '交易货币代码-b049',
  `b051_chb_curr_code` varchar(3) NOT NULL DEFAULT '' COMMENT '账户货币代码-b051',
  `b037_ref_nbr` varchar(12) NOT NULL DEFAULT '' COMMENT '检索参考号-b037',
  `b028_fee` varchar(9) NOT NULL DEFAULT '' COMMENT '手续费-B028',
  `b048_add` varchar(999) NOT NULL DEFAULT '' COMMENT '附加数据-b048',
  `b054_resp` varchar(60) NOT NULL DEFAULT '' COMMENT '返回余额数组-b054',
  `trans_medium` varchar(32) NOT NULL DEFAULT '' COMMENT '交易介质',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `txn_input_source` varchar(40) NOT NULL DEFAULT '' COMMENT '交易来源 ',
  `bound` varchar(2) NOT NULL DEFAULT '' COMMENT '境内外标记 ',
  `counterpart_no` varchar(40) NOT NULL DEFAULT '' COMMENT '对方账号卡号 ',
  `counterpart_name` varchar(40) NOT NULL DEFAULT '' COMMENT '对方名称 ',
  `counterpart_address` varchar(80) NOT NULL DEFAULT '' COMMENT '对方地址 ',
  `txn_desc` varchar(64) NOT NULL DEFAULT '' COMMENT '交易描述 ',
  `b019` varchar(20) NOT NULL DEFAULT '' COMMENT 'b019 ',
  `orig_trace_nbr` varchar(6) NOT NULL DEFAULT '' COMMENT '原交易系统跟踪号 ',
  `amt_direction` varchar(3) NOT NULL DEFAULT '' COMMENT '金额方向',
  `show_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '对客展示标识',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_authmemo_inq_log` (`log_kv`) USING BTREE,
  KEY `idx_ccs_authmemo_inq_log_1` (`acct_nbr`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_authmemo_inq_log' ;
CREATE TABLE `auth_order_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '授权流水号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` char(1) NOT NULL DEFAULT '' COMMENT '账户类型',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `lmt_node_cd` varchar(32) NOT NULL DEFAULT '' COMMENT '额度节点',
  `lmt_type` varchar(16) NOT NULL DEFAULT '' COMMENT '额度类型',
  `acq_ref_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '受理机构交易编码',
  `txn_scene_list` varchar(255) NOT NULL DEFAULT '' COMMENT '交易场景列表',
  `txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '交易金额',
  `txn_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '交易币种代码',
  `auth_code` varchar(6) NOT NULL DEFAULT '' COMMENT '授权码',
  `loan_code` varchar(16) NOT NULL DEFAULT '' COMMENT '分期产品代码',
  `acq_address` varchar(64) NOT NULL DEFAULT '' COMMENT '受理机构名称地址',
  `chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '持卡人账户币种金额',
  `chb_currency` varchar(3) NOT NULL DEFAULT '' COMMENT '持卡人账户币种',
  `input_source` varchar(15) NOT NULL DEFAULT '' COMMENT '交易渠道',
  `mcc` varchar(4) NOT NULL DEFAULT '' COMMENT '商户类型',
  `acq_branch_iq` varchar(11) NOT NULL DEFAULT '' COMMENT '受理分行代码',
  `fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '转发机构号',
  `transport_time` varchar(10) NOT NULL DEFAULT '' COMMENT '传送日期',
  `settle_date` varchar(4) NOT NULL DEFAULT '' COMMENT '清算日期',
  `txn_direction` varchar(20) NOT NULL DEFAULT '' COMMENT '交易方向',
  `auth_txn_terminal` varchar(40) NOT NULL DEFAULT '' COMMENT '交易终端',
  `auth_txn_status` char(1) NOT NULL DEFAULT '' COMMENT '授权状态',
  `txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '交易类型',
  `log_ol_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT 'log联机时间',
  `log_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '联机业务日期',
  `mti` varchar(4) NOT NULL DEFAULT '' COMMENT '交易类型标识',
  `orig_txn_type` varchar(20) NOT NULL DEFAULT '' COMMENT '原交易类型',
  `orig_fwd_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始转发机构号',
  `orig_acq_inst_id` varchar(11) NOT NULL DEFAULT '' COMMENT '原始受理机构号',
  `orig_mti` varchar(4) NOT NULL DEFAULT '' COMMENT '原交易mti',
  `orig_txn_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易日期',
  `orig_trace_no` varchar(6) NOT NULL DEFAULT '' COMMENT '原始系统跟踪号',
  `orig_txn_proc` varchar(6) NOT NULL DEFAULT '' COMMENT '原交易处理码',
  `orig_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始交易币种金额',
  `orig_log_kv` varchar(32) NOT NULL DEFAULT '' COMMENT '原交易log键值',
  `orig_txn_val_1` varchar(38) NOT NULL DEFAULT '' COMMENT '原交易键值1',
  `orig_txn_val_2` varchar(85) NOT NULL DEFAULT '' COMMENT '原交易键值2',
  `orig_chb_txn_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原始入账币种金额',
  `orig_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '原交易的联机业务处理日期',
  `last_reversal_date` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '最后一次冲撤时间',
  `void_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '撤销次数',
  `manual_auth_flag` char(1) NOT NULL DEFAULT '' COMMENT '人工授权标志',
  `op_id` varchar(40) NOT NULL DEFAULT '' COMMENT '操作员id',
  `card_association` varchar(2) NOT NULL DEFAULT '' COMMENT '卡组织品牌',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `mcc_type` varchar(2) NOT NULL DEFAULT '' COMMENT '商户类型分组',
  `final_reason` varchar(4) NOT NULL DEFAULT '' COMMENT '授权原因',
  `final_action` char(1) NOT NULL DEFAULT '' COMMENT '最终行动',
  `final_auth_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终授权金额',
  `final_upd_direction` char(1) NOT NULL DEFAULT '' COMMENT '最终更新方向',
  `final_upd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '最终更新金额',
  `ic_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否ic卡',
  `the_3dsecure_type` char(1) NOT NULL DEFAULT '' COMMENT '是否3d电子安全交易',
  `vip_status` char(1) NOT NULL DEFAULT '' COMMENT 'vip状态',
  `curr_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当前余额',
  `cash_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现金额',
  `otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '可用额度',
  `cash_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '取现可用额度',
  `cust_otb` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '客户可用额度',
  `in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '账户黑名单标识',
  `mer_in_blacklist_ind` varchar(20) NOT NULL DEFAULT '' COMMENT '是否商户黑名单',
  `date_expire` varchar(4) NOT NULL DEFAULT '' COMMENT '卡面有效期',
  `megt1_result` varchar(20) NOT NULL DEFAULT '' COMMENT '一磁道完整性结果',
  `megt2_result` varchar(20) NOT NULL DEFAULT '' COMMENT '二磁道完整性结果',
  `megt3_result` varchar(20) NOT NULL DEFAULT '' COMMENT '三磁道完整性结果',
  `pwd_type` char(1) NOT NULL DEFAULT '' COMMENT '密码种类',
  `pwd_result` varchar(20) NOT NULL DEFAULT '' COMMENT '验证密码结果',
  `pay_pwd_err_num` int(11) NOT NULL DEFAULT '0' COMMENT '支付密码错误次数',
  `cvv_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv验证结果',
  `cvv2_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvv2验证结果',
  `icvn_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'icvn验证结果',
  `arqc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'arqc验证结果',
  `atc_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'atc验证结果',
  `cvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'cvr验证结果',
  `tvr_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'tvr验证结果',
  `rej_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '拒绝原因',
  `memo_cr` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配贷记金额',
  `memo_db` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配借记金额',
  `b002_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '介质卡号-b002',
  `b003_proc_code` varchar(6) NOT NULL DEFAULT '' COMMENT '交易处理码-b003',
  `b004_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '交易金额-B004',
  `b007_txn_time` varchar(10) NOT NULL DEFAULT '' COMMENT '交易传输时间-b007',
  `b011_trace` varchar(6) NOT NULL DEFAULT '' COMMENT '系统跟踪号-b011',
  `b022_entrymode` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点pin获取码-b022',
  `b025_entrycond` varchar(4) NOT NULL DEFAULT '' COMMENT '服务点条件码-b025',
  `b032_acq_inst` varchar(15) NOT NULL DEFAULT '' COMMENT '受理机构标识码-b032',
  `b033_fwd_ins` varchar(40) NOT NULL DEFAULT '' COMMENT '受理机构名称地址-b033',
  `b039_rtn_code` varchar(2) NOT NULL DEFAULT '' COMMENT '返回码-b039',
  `b042_mer_id` varchar(15) NOT NULL DEFAULT '' COMMENT '受卡方(商户)标识码-b042',
  `b060_reserved` varchar(103) NOT NULL DEFAULT '' COMMENT '自定义域-b060',
  `b061_cust_info` varchar(203) NOT NULL DEFAULT '' COMMENT '持卡人身份认证信息-b061',
  `b090_orig_data` varchar(42) NOT NULL DEFAULT '' COMMENT '原始数据元',
  `op_term_id` varchar(20) NOT NULL DEFAULT '' COMMENT '操作用户终端编号',
  `b006_chb_amt` varchar(12) NOT NULL DEFAULT '' COMMENT '账户货币金额-B006',
  `b049_curr_code` varchar(3) NOT NULL DEFAULT '' COMMENT '交易货币代码-b049',
  `b051_chb_curr_code` varchar(3) NOT NULL DEFAULT '' COMMENT '账户货币代码-b051',
  `b037_ref_nbr` varchar(12) NOT NULL DEFAULT '' COMMENT '检索参考号-b037',
  `b028_fee` varchar(9) NOT NULL DEFAULT '' COMMENT '手续费-B028',
  `b048_add` varchar(999) NOT NULL DEFAULT '' COMMENT '附加数据-b048',
  `b054_resp` varchar(60) NOT NULL DEFAULT '' COMMENT '返回余额数组-b054',
  `b063_network_data` varchar(20) NOT NULL DEFAULT '' COMMENT '网络数据-b063',
  `acq_terminal_id` varchar(8) NOT NULL DEFAULT '' COMMENT '受理机构终端标识码',
  `post_online` char(1) NOT NULL DEFAULT '' COMMENT '联机入账标识',
  `match_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否匹配',
  `b056` varchar(20) NOT NULL DEFAULT '' COMMENT '56域',
  `trans_medium` varchar(32) NOT NULL DEFAULT '' COMMENT '交易介质',
  `conversion_rt` decimal(8,6) NOT NULL DEFAULT '0.000000' COMMENT '兑换汇率',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `stat_lmt_scene_list` varchar(2048) NOT NULL DEFAULT '' COMMENT '累计限额场景列表',
  `txn_input_source` varchar(40) NOT NULL DEFAULT '' COMMENT '交易来源 ',
  `txn_desc` varchar(64) NOT NULL DEFAULT '' COMMENT '交易描述 ',
  `bound` varchar(2) NOT NULL DEFAULT '' COMMENT '境内外标记 ',
  `counterpart_no` varchar(40) NOT NULL DEFAULT '' COMMENT '对方账号卡号 ',
  `counterpart_name` varchar(40) NOT NULL DEFAULT '' COMMENT '对方名称 ',
  `counterpart_address` varchar(80) NOT NULL DEFAULT '' COMMENT '对方地址 ',
  `retail_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '刷卡金使用金额 ',
  `credit_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '还款金使用金额 ',
  `mer_data` varchar(200) NOT NULL DEFAULT '' COMMENT '商户信息 ',
  `assign_pay_branch_nbr` varchar(15) NOT NULL DEFAULT '' COMMENT '指定部门还款部门号 ',
  `txn_attribute` varchar(300) NOT NULL DEFAULT '' COMMENT '交易附属信息 ',
  `orig_trace_nbr` varchar(6) NOT NULL DEFAULT '' COMMENT '原交易系统跟踪号 ',
  `orig_local_time` varchar(14) NOT NULL DEFAULT '' COMMENT '原交易报文日期时间 ',
  `b019` varchar(20) NOT NULL DEFAULT '' COMMENT 'b019 ',
  `b095_replace_amt` varchar(42) NOT NULL DEFAULT '' COMMENT 'B95替换金额',
  `b112_addl_data` varchar(100) NOT NULL DEFAULT '' COMMENT 'B112附加数据',
  `b121_auth_agentid` varchar(6) NOT NULL DEFAULT '' COMMENT 'B121授权代理ID代码',
  `amt_direction` varchar(3) NOT NULL DEFAULT '' COMMENT '金额方向',
  `show_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '对客展示标识',
  `b013_local_date` varchar(4) NOT NULL DEFAULT '' COMMENT 'DE13域本地交易日期MMDD',
  `b012_local_time` varchar(6) NOT NULL DEFAULT '' COMMENT 'DE12本地交易时间HHMMSS',
  `b4842_ecommerce_ind` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4842电子商务指标',
  `b4843_ucaf` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4843通用持卡人身份验证',
  `b4866_auth_data` varchar(45) NOT NULL DEFAULT '' COMMENT 'DE4866认证数据',
  `b4871_ob_services` varchar(40) NOT NULL DEFAULT '' COMMENT 'DE4871交易支持服务',
  `b4875_fraud_score` varchar(32) NOT NULL DEFAULT '' COMMENT 'DE4875交易风险评分',
  `cvm_result_9f34` varchar(6) NOT NULL DEFAULT '' COMMENT 'DE55_9F34',
  `loan_term` int(11) NOT NULL DEFAULT '0' COMMENT '分期期数',
  `b0120` varchar(1024) NOT NULL DEFAULT '' COMMENT 'DE120域',
  `b0124` varchar(1024) NOT NULL DEFAULT '' COMMENT 'DE124域',
  `b122_addl` varchar(999) NOT NULL DEFAULT '' COMMENT 'DE122',
  `virtual_ind` varchar(1) NOT NULL DEFAULT '' COMMENT '虚拟卡标识',
  `advice_de39` varchar(2) NOT NULL DEFAULT '' COMMENT '通知交易39域信息',
  `auth_reason_list` varchar(999) NOT NULL DEFAULT '' COMMENT '授权原因码列表',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_authmemo_o` (`log_kv`) USING BTREE,
  KEY `idx_ccs_authmemo_o_1` (`acct_nbr`) USING BTREE,
  KEY `idx_memo_bizdate` (`log_biz_date`),
  KEY `idx_match_ind` (`match_ind`),
  KEY `idx_ci_tc` (`cust_id`,`txn_currency`),
  KEY `idx_lcn_tt` (`logic_card_nbr`,`txn_type`),
  KEY `idx_final_action` (`final_action`),
  KEY `idx_b002cardNbr` (`b002_card_nbr`),
  KEY `idx_log_ol_time` (`log_ol_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_authmemo_o' ;
CREATE TABLE `ccs_blk_operater_hst_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `org` varchar(20) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `acct_type` varchar(2) NOT NULL DEFAULT '' COMMENT '账户类型',
  `card_token` varchar(64) NOT NULL DEFAULT '' COMMENT '卡编号',
  `opt_name` varchar(32) NOT NULL DEFAULT '' COMMENT '操作员',
  `opt_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `belong_sys` varchar(60) NOT NULL DEFAULT '' COMMENT '业务属主',
  `blk_cd` varchar(4) NOT NULL DEFAULT '' COMMENT '管制码值',
  `memo1` varchar(64) NOT NULL DEFAULT '' COMMENT 'memo1',
  `memo2` varchar(1024) NOT NULL DEFAULT '' COMMENT 'memo2',
  `priority` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '优先级',
  `opt_action` varchar(2) NOT NULL DEFAULT '' COMMENT '动作来源，m 手动， d 自动',
  `blk_action` varchar(7) NOT NULL DEFAULT '' COMMENT '锁定码动作，up - 上码， down - 下码',
  `act_ind` varchar(2) NOT NULL DEFAULT '' COMMENT '生效标识',
  `blk_level` varchar(20) NOT NULL DEFAULT '' COMMENT '锁定码层级',
  `channel_code` varchar(20) NOT NULL DEFAULT '' COMMENT '渠道代码',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE,
  KEY `idx_acct_type` (`acct_type`),
  KEY `idx_cust_id` (`cust_id`),
  KEY `idx_card_token` (`card_token`),
  KEY `idx_acct_nbr` (`acct_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='管制码操作日志表' ;
CREATE TABLE `ccs_card_acq_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `acquirer_id` varchar(11) NOT NULL DEFAULT '' COMMENT '收单行编号',
  `dtd_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当日累计笔数',
  `dtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日累计金额',
  `month_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当月累计笔数',
  `month_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当月累计金额',
  `year_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当年累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_card_acq_id` (`logic_card_nbr`,`acquirer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ccs_card_acq_stat : 收单行累计表' ;
alter table `ccs_card_acq_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_card_o_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `bsc_supp_ind` char(1) NOT NULL DEFAULT '' COMMENT '主附卡标识',
  `basic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '主卡逻辑卡号',
  `corp_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '商务主卡号',
  `auth_tag` varchar(255) NOT NULL DEFAULT '' COMMENT '授权标识',
  `policy_ind` char(1) NOT NULL DEFAULT '' COMMENT '限额开关',
  `blk_cd_auth` varchar(27) NOT NULL DEFAULT '' COMMENT '授权锁定码',
  `blk_cd_post` varchar(27) NOT NULL DEFAULT '' COMMENT '账务锁定码',
  `active_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否已激活',
  `pos_pin_verify_ind` char(1) NOT NULL DEFAULT '' COMMENT '是否消费凭密',
  `pos_pin_verify_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '小额免密金额上限',
  `pin_tries` int(11) NOT NULL DEFAULT '0' COMMENT '交易密码错误次数',
  `last_update_biz_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '上次联机更新业务日期',
  `last_pin_tries_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '上次密码错时间',
  `inq_pin_tries` int(11) NOT NULL DEFAULT '0' COMMENT '查询密码错误次数',
  `last_inq_pin_tries_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '上次查询密码错误时间',
  `day_used_atm_cupxb_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日atm银联境外取现金额',
  `hiding_credit_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '高端卡隐藏额度',
  `sms_receiver` char(1) NOT NULL DEFAULT '' COMMENT '单一货币结算标识 ',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `test` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为测试数据：0-否；1-是',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_card_o` (`logic_card_nbr`) USING BTREE,
  KEY `idx_cust_id` (`cust_id`),
  KEY `idx_pin_tries` (`pin_tries`),
  KEY `idx_acct_nbr` (`acct_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_card_o' ;
alter table `ccs_card_o_{0,255}` add column `virtual_ind` char(1) NOT NULL DEFAULT '' COMMENT '虚拟卡标识' after `bsc_supp_ind`;
alter table ccs_card_o_{0,255} add column `card_token` varchar(64) NOT NULL DEFAULT '' COMMENT '卡token' after `logic_card_nbr`;
CREATE TABLE `ccs_card_scene_policy_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `currency` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `policy_tag` varchar(16) NOT NULL DEFAULT '' COMMENT '限额标签',
  `lt_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单笔限额',
  `st_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单笔限额',
  `st_txn_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额开始日期',
  `st_txn_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额结束日期',
  `lt_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单日限笔',
  `st_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单日限笔',
  `st_day_cnt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔开始日期',
  `st_day_cnt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔结束日期',
  `lt_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单日限额',
  `st_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单日限额',
  `st_day_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额开始日期',
  `st_day_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额结束日期',
  `lt_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单月限额',
  `st_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单月限额',
  `st_mon_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额开始日期',
  `st_mon_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额结束日期',
  `lt_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单年限额',
  `st_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单年限额',
  `st_year_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额开始日期',
  `st_year_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额结束日期',
  `lt_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单月限笔',
  `st_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单月限笔',
  `st_mon_cnt_beg_date` date NOT NULL DEFAULT '1970-01-01' COMMENT '临时单月限笔开始日期',
  `st_mon_cnt_end_date` date NOT NULL DEFAULT '1970-01-01' COMMENT '临时单月限笔结束日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `st_stmt_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时当期限额开始日期 ',
  `st_stmt_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时当期结束日期 ',
  `st_stmt_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时当期限额',
  `lt_stmt_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期当期限额',
  `auth_ind` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '是否支持本币交易',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_card_scene_policy` (`logic_card_nbr`,`currency`,`txn_scene`,`policy_tag`) USING BTREE,
  KEY `idx_card_currency_scene` (`logic_card_nbr`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_card_scene_policy' ;
CREATE TABLE `ccs_card_scene_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `currency` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `dtd_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当日累计笔数',
  `mon_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当月累计笔数',
  `dtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日累计金额',
  `mtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当月累计金额',
  `ytd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当年累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `ctd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '临时当期限额 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_card_scene_stat` (`logic_card_nbr`,`currency`,`txn_scene`) USING BTREE,
  KEY `idx_card_currency_scene` (`logic_card_nbr`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_card_scene_stat' ;
CREATE TABLE `ccs_country_group_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `country_group_card` varchar(64) NOT NULL DEFAULT '' COMMENT '国家组号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_idx_card_country_group` (`logic_card_nbr`,`country_group_card`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='国家组累计表' ;
alter table `ccs_country_group_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_cust_auth_ctrl_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户号',
  `msi_ind` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '是否支持msi',
  `manual_release_ind` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '是否支持手工释放',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_cust_id` (`cust_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ccs_cust_auth_ctrl : 客户授权控制表' ;
CREATE TABLE `ccs_cust_o_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `cust_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客户姓名',
  `gender` char(1) NOT NULL DEFAULT '' COMMENT '性别',
  `id_type` char(1) NOT NULL DEFAULT '' COMMENT '证件类型',
  `id_no` varchar(64) NOT NULL DEFAULT '' COMMENT '证件号码',
  `mobile_no` varchar(20) NOT NULL DEFAULT '' COMMENT '移动电话',
  `cust_tag` varchar(128) NOT NULL DEFAULT '' COMMENT '客户标签',
  `auth_tag` varchar(255) NOT NULL DEFAULT '' COMMENT '授权标识',
  `policy_ind` char(1) NOT NULL DEFAULT '' COMMENT '限额开关',
  `blk_cd_auth` varchar(27) NOT NULL DEFAULT '' COMMENT '授权锁定码',
  `blk_cd_post` varchar(27) NOT NULL DEFAULT '' COMMENT '账务锁定码',
  `blk_cd_post_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '账务锁定码同步日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `test` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为测试数据：0-否；1-是',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_cust_o` (`cust_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_cust_o' ;
alter table `ccs_cust_o_{0,255}` add column `email` varchar(255) NOT NULL DEFAULT '' COMMENT '电子邮箱' after `mobile_no`;
CREATE TABLE `ccs_cust_scene_policy_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `currency` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `policy_tag` varchar(16) NOT NULL DEFAULT '' COMMENT '限额标签',
  `lt_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单笔限额',
  `st_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单笔限额',
  `st_txn_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额开始日期',
  `st_txn_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单笔限额结束日期',
  `lt_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单日限笔',
  `st_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单日限笔',
  `st_day_cnt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔开始日期',
  `st_day_cnt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限笔结束日期',
  `lt_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单日限额',
  `st_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单日限额',
  `st_day_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额开始日期',
  `st_day_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单日限额结束日期',
  `lt_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单月限额',
  `st_mon_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单月限额',
  `st_mon_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额开始日期',
  `st_mon_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单月限额结束日期',
  `lt_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '长期单年限额',
  `st_year_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '临时单年限额',
  `st_year_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额开始日期',
  `st_year_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时单年限额结束日期',
  `lt_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '长期单月限笔',
  `st_mon_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '临时单月限笔',
  `st_mon_cnt_beg_date` date NOT NULL DEFAULT '1970-01-01' COMMENT '临时单月限笔开始日期',
  `st_mon_cnt_end_date` date NOT NULL DEFAULT '1970-01-01' COMMENT '临时单月限笔结束日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `auth_ind` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '是否支持本币交易',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_cust_scene_policy` (`cust_id`,`currency`,`txn_scene`,`policy_tag`) USING BTREE,
  KEY `idx_cust_currency_scene` (`cust_id`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_cust_scene_policy' ;
CREATE TABLE `ccs_cust_scene_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `currency` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `dtd_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当日累计笔数',
  `dtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日累计金额',
  `mtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当月累计金额',
  `ytd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当年累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `mon_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当月累计笔数',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_cust_scene_stat` (`cust_id`,`currency`,`txn_scene`) USING BTREE,
  KEY `idx_cust_currency_scene` (`cust_id`,`currency`,`txn_scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_cust_scene_stat' ;
CREATE TABLE `ccs_lmt_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `product_cd` varchar(16) NOT NULL DEFAULT '' COMMENT '产品代码',
  `lmt_node_cd` varchar(32) NOT NULL DEFAULT '' COMMENT '额度节点',
  `lmt_desc` varchar(64) NOT NULL DEFAULT '' COMMENT '额度描述',
  `lmt_type` varchar(16) NOT NULL DEFAULT '' COMMENT '额度类型',
  `credit_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '信用额度',
  `temp_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '临时额度',
  `temp_lmt_beg_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时额度开始日期',
  `temp_lmt_end_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '临时额度结束日期',
  `memo_db_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '未匹配借记笔数',
  `memo_db` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配借记金额',
  `memo_cr_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '未匹配贷记笔数',
  `memo_cr` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '未匹配贷记金额',
  `xfr_out_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '分期未下账金额',
  `curr_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当前余额',
  `deposit_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '溢缴款',
  `dispute_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '争议金额',
  `dual_memo_db_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币借记备忘笔数',
  `dual_memo_db` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币借记备忘',
  `dual_memo_cr_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币贷记备忘笔数',
  `dual_memo_cr` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币贷记备忘',
  `dual_xfr_out_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币分期未下账金额',
  `dual_curr_bal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币余额',
  `dual_deposit_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币溢缴款',
  `dual_dispute_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币争议金额',
  `node_rate` decimal(8,6) NOT NULL DEFAULT '0.000000' COMMENT '节点占比',
  `ovl_rate` decimal(8,6) NOT NULL DEFAULT '0.000000' COMMENT '超限比例',
  `parent` varchar(16) NOT NULL DEFAULT '' COMMENT '父节点号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `post_update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '入账机器时间',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_ccs_lmt` (`acct_nbr`,`lmt_node_cd`) USING BTREE,
  KEY `idx_cust_id` (`cust_id`),
  KEY `idx_acct_type` (`acct_nbr`,`lmt_type`),
  KEY `idx_temp_end_date` (`temp_lmt_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_lmt' ;
CREATE TABLE `ccs_lmt_adj_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `acct_nbr` varchar(32) NOT NULL DEFAULT '' COMMENT '账户编号',
  `lmt_node_cd` varchar(32) NOT NULL DEFAULT '' COMMENT '额度节点',
  `lmt_adj_type` varchar(16) NOT NULL DEFAULT '' COMMENT '额度调整类型',
  `lmt_adj_result` char(1) NOT NULL DEFAULT '' COMMENT '额度调整结果',
  `lmt_adj_memo` varchar(255) NOT NULL DEFAULT '' COMMENT '额度调整备注',
  `orig_info` varchar(255) NOT NULL DEFAULT '' COMMENT '原始信息',
  `curr_info` varchar(255) NOT NULL DEFAULT '' COMMENT '当前信息',
  `apply_seq` varchar(32) NOT NULL DEFAULT '' COMMENT '申请流水号',
  `apply_system` varchar(16) NOT NULL DEFAULT '' COMMENT '申请系统',
  `apply_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '申请日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE,
  KEY `idx_ccs_lmt_adj_1` (`cust_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_lmt_adj' ;
alter table ccs_lmt_adj_{0,255} add UNIQUE KEY `uniq_apply_seq_apply_system` (`apply_seq`,`apply_system`);
CREATE TABLE `ccs_lmt_scene_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `acct_nbr` varchar(45) NOT NULL DEFAULT '' COMMENT '账户账号',
  `scene_type` varchar(45) NOT NULL DEFAULT '' COMMENT '场景类型',
  `scene_value` varchar(200) NOT NULL DEFAULT '' COMMENT '场景取值',
  `scene_status` varchar(10) NOT NULL DEFAULT 'init' COMMENT '场景取值@unable：失效-@able:生效- @init:初始化',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_acct_nbr_scene_type` (`acct_nbr`,`scene_type`),
  KEY `idx_acct_nbr` (`acct_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='场景额度信息表' ;
CREATE TABLE `ccs_manual_release_stat` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `manual_stat_type` varchar(15) NOT NULL DEFAULT '' COMMENT '手工释放累计类型',
  `manual_stat_value` varchar(15) NOT NULL DEFAULT '' COMMENT '手工释放累计类型值',
  `dtd_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当日累计笔数',
  `dtd_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当日累计金额',
  `mon_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '当月累计笔数',
  `mon_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当月累计金额',
  `year_amt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '当年累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_manual_type_value` (`manual_stat_type`,`manual_stat_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ccs_manual_release_stat : 手工释放累计表' ;
CREATE TABLE `ccs_mcc_merchant_parameter_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `mcc` varchar(100) NOT NULL DEFAULT '' COMMENT 'mcc',
  `merchant` varchar(300) NOT NULL DEFAULT '' COMMENT '商户',
  `mcc_merchant` varchar(64) NOT NULL DEFAULT '' COMMENT '标识id',
  `local_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '本币单笔限额',
  `local_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '本币单日限笔',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '本币单日限额',
  `local_transaction` char(1) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '本币是否允许交易',
  `local_down_transaction` char(1) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '本币是否允许降级交易',
  `foreign_txn_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '外币单笔限额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '外币单日限笔',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '-1.00' COMMENT '外币单日限额',
  `foreign_transaction` char(1) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '外币是否允许交易',
  `foreign_down_transaction` char(1) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '外币是否允许降级交易',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE,
  KEY `idx_card_mcc_merch` (`logic_card_nbr`,`mcc`,`merchant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='mcc商户参数表' ;
alter table `ccs_mcc_merchant_parameter_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
alter table ccs_mcc_merchant_parameter_{0,255} add UNIQUE KEY `uniq_cust_id_mcc_merchant` (`cust_id`,`mcc`,`merchant`);
CREATE TABLE `ccs_mcc_merchant_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `mcc_merchant` varchar(64) NOT NULL DEFAULT '' COMMENT '标识id',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_idx_mcc_merchant` (`mcc_merchant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='mcc商户累计表' ;
alter table `ccs_mcc_merchant_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_mcc_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `mcc_card` varchar(19) NOT NULL DEFAULT '' COMMENT 'mcc号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  `input_source` varchar(10) NOT NULL DEFAULT '' COMMENT '接入卡组织 ',
  PRIMARY KEY (`pid`) USING BTREE,
  KEY `idx_card_mcc_source` (`logic_card_nbr`,`mcc_card`,`input_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='mcc累计表' ;
alter table ccs_mcc_stat_{0,255} add UNIQUE KEY `uniq_logic_card_nbr_mcc_card_input_source` (`logic_card_nbr`,`mcc_card`,`input_source`);
CREATE TABLE `ccs_mcg_group_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `mcg_group_card` varchar(64) NOT NULL DEFAULT '' COMMENT 'mcg组号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_idx_card_mcg` (`logic_card_nbr`,`mcg_group_card`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='mcg组累计表' ;
alter table `ccs_mcg_group_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_merchant_authorization_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `merchant_card` varchar(15) NOT NULL DEFAULT '' COMMENT '商户号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `txn_scene` varchar(64) NOT NULL DEFAULT '' COMMENT '交易场景',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_card_merchant_scene` (`logic_card_nbr`,`merchant_card`,`txn_scene`),
  KEY `idx_card_nbr` (`logic_card_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='商户授权累计表' ;
alter table `ccs_merchant_authorization_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_merchant_group_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` char(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `merchant_group_card` varchar(64) NOT NULL DEFAULT '' COMMENT '商户组号',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `foreign_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '外币单日累计笔数',
  `foreign_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '外币单日累计金额',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE KEY `uniq_idx_card_merchant_group` (`logic_card_nbr`,`merchant_group_card`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='商户组累计表' ;
alter table `ccs_merchant_group_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `org`;
CREATE TABLE `ccs_merchant_key_group_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `key_group_id` varchar(64) NOT NULL DEFAULT '' COMMENT '商户名关键字组id',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_idx_card_group_id` (`logic_card_nbr`,`key_group_id`),
  KEY `idx_card_no` (`logic_card_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='商户名关键字组累计表' ;
alter table `ccs_merchant_key_group_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `logic_card_nbr`;
CREATE TABLE `ccs_pin_temp` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `card_token` varchar(64) NOT NULL DEFAULT '' COMMENT '卡tokne',
  `pin_block` varchar(16) NOT NULL DEFAULT '' COMMENT 'pinblock',
  `pin_offset` varchar(16) NOT NULL DEFAULT '' COMMENT 'pinoffset',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_idx_card_token` (`card_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='pin临时表' ;
CREATE TABLE `ccs_lmt_cc_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `org` varchar(12) NOT NULL DEFAULT '' COMMENT '机构号',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号',
  `lmt_node_cd` varchar(32) NOT NULL DEFAULT '' COMMENT '额度节点',
  `lmt_desc` varchar(64) NOT NULL DEFAULT '' COMMENT '额度描述',
  `currency` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `credit_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '信用额度',
  `node_rate` decimal(8,6) NOT NULL DEFAULT '0.000000' COMMENT '节点占比',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='ccs_lmt_cc' ;
alter table `ccs_lmt_cc_{0,255}` add UNIQUE KEY `uniq_cust_id_lmt_node_cd` (`cust_id`,`lmt_node_cd`);
CREATE TABLE `ccs_lmt_apply_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `apply_seq` varchar(100) NOT NULL DEFAULT '' COMMENT '申请流水号',
  `apply_system` varchar(36) NOT NULL DEFAULT '' COMMENT '申请渠道',
  `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户号',
  `trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'traceid',
  `req_param` varchar(500) NOT NULL DEFAULT '' COMMENT '请求参数json',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '业务日期',
  `provider_type` varchar(32) NOT NULL DEFAULT '' COMMENT '服务端渠道类型',
  `apply_status` varchar(36) NOT NULL DEFAULT '' COMMENT '申请状态',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_apply_seq_system` (`apply_seq`,`apply_system`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='额度申请表' ;
CREATE TABLE `ccs_merchant_terminal_stat_{0,255}` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `logic_card_nbr` varchar(64) NOT NULL DEFAULT '' COMMENT '逻辑卡号',
  `merchant` varchar(15) NOT NULL DEFAULT '' COMMENT '商户号',
  `terminal` varchar(8) NOT NULL DEFAULT '' COMMENT '终端号',
  `local_day_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '本币单日累计笔数',
  `local_day_lmt` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本币单日累计金额',
  `proc_date` date NOT NULL DEFAULT '1971-01-01' COMMENT '处理日期 ',
  `create_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '更新时间',
  `jpa_version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uniq_idx_merchant_terminal` (`logic_card_nbr`,`merchant`,`terminal`),
  KEY `idx_card_no` (`logic_card_nbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='商户终端累计表' ;
alter table `ccs_merchant_terminal_stat_{0,255}` add column `cust_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户编号' after `logic_card_nbr`;
